name: Documentation

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'CLAUDE.md'
      - 'ORCHESTRATOR.md'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'CLAUDE.md'
      - 'ORCHESTRATOR.md'

jobs:
  validate:
    name: Validate Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run documentation checks
        run: |
          chmod +x scripts/check-docs.sh
          ./scripts/check-docs.sh

      - name: Check for broken links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: '.github/markdown-link-check-config.json'

  lint:
    name: Lint Markdown
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint markdown files
        uses: avto-dev/markdown-lint@v1
        with:
          args: 'docs/'
          config: '.markdownlint.json'
          ignore: 'docs/templates/'

  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check spelling
        uses: rojopolis/spellcheck-github-actions@0.35.0
        with:
          config_path: '.github/spellcheck-config.yml'
          task_name: Markdown
